config/routes.rb
Rails.application.routes.draw do
  get 'pages/about'
  devise_for :users, controllers: {
    registrations: "users/registrations", sessions: "users/sessions", confirmations: "users/confirmations" }
  root "products#index"
  devise_scope :user do
    get "new_user", to: "users/registrations#new_user"
    post "new_user", to: "users/registrations#create_user"
    get "addresses", to: "users/registrations#new_address"
    post "addresses", to: "users/registrations#create_address"
    get "edit_addresses", to: "users/registrations#edit_address"
    patch "edit_addresses", to: "users/registrations#update_address"
  end

  resources :products do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    member do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
  end

  resources :categories, only: [:index, :show]

  resources :cards, only: [:new, :create, :show, :destroy]

  resources :carts, only: [:show, :destroy] do
    collection do
      post 'add_product'
    end
  end

  resources :orders, only: [:new, :create, :index] do
    collection do
      get 'confirm'
    end
  end 

  resources :order_details, only: :index

  resources :cart_details

  get 'about', to: 'pages#about'
  get 'privacy', to: 'pages#privacy'
  # get 'faq', to: 'pages#faq'
  get 'delivery', to: 'pages#delivery'
  get 'refund', to: 'pages#refund'
  get 'terms_of_service', to: 'pages#terms_of_service'
  get 'tokushoho', to: 'pages#tokushoho'
  get 'inquiry', to: 'pages#inquiry'
  get 'search', to: 'pages#search'
  get 'search_result', to: 'pages#search_result'

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :products, through: :order_details
  has_many :order_details, dependent: :destroy
  belongs_to :card
  belongs_to :address

  # enum status: {支払済み: 0, 配送準備中: 1, 配送済み: 2}

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_cart
  before_action :user_signed_in
  before_action :set_user
  before_action :set_card
  before_action :set_address

  require "payjp"

  #注文入力画面
  def new
    @cart_details = current_cart.cart_details
    @cart = current_cart
    if @cart.cart_details.empty?
      redirect_to current_cart, notice: "カートは空です"
      return
    end
    if @card.present?
      customer = Payjp::Customer.retrieve(@card.customer_id)
      default_card_information = customer.cards.retrieve(@card.card_id)
      @card_info = customer.cards.retrieve(@card.card_id)
      @exp_month = default_card_information.exp_month.to_s
      @exp_year = default_card_information.exp_year.to_s.slice(2,3)
      customer_card = customer.cards.retrieve(@card.card_id)
      @card_brand = customer_card.brand
      case @card_brand
      when "Visa"
        @card_src = "https://www-mercari-jp.akamaized.net/assets/img/card/visa.svg?238737266"
      when "MasterCard"
        @card_src = "https://www-mercari-jp.akamaized.net/assets/img/card/master-card.svg?238737266"
      when "JCB"
        @card_src = "https://www-mercari-jp.akamaized.net/assets/img/card/jcb.svg?238737266"
      when "American Express"
        @card_src = "https://www-mercari-jp.akamaized.net/assets/img/card/american_express.svg?238737266"
      when "Diners Club"
        @card_src = "https://www-mercari-jp.akamaized.net/assets/img/card/dinersclub.svg?238737266"
      when "Discover"
        @card_src = "https://www-mercari-jp.akamaized.net/assets/img/card/discover.svg?238737266"
      end
      @order = Order.new
    end
  end

  #注文の登録
  def create
    unless user_signed_in?
      redirect_to cart_path(@current_cart), notice: "ログインしてください"
      return
    end

    ActiveRecord::Base.transaction do
      @order = Order.new(order_params)
      @order.save!
      # raise "エラーがおきました"
      OrderDetail.adjustStock_createDetail(@order, @cart.cart_details)
    rescue
      flash[:alert] = '発注数量確認の上、再度お試し下さい。'
      redirect_to root_path
      return
    end

    @purchaseByCard = Payjp::Charge.create(
    amount: @cart.total_price,
    customer: @card.customer_id,
    currency: 'jpy',
    card: params['payjpToken']
    )

    if @purchaseByCard.save
      NotificationMailer.send_order_confirm(@user).deliver
      # flash[:notice] = '注文が完了しました。マイページにて注文履歴の確認ができます。' #注文履歴作成予定
      flash[:notice] = '注文が完了しました。'
      redirect_to action: :confirm
    else

      flash[:alert] = "注文の登録ができませんでした。"
      redirect_to action: :new
    end
  end

  def confirm
    @order = Order.order(created_at: :desc).find_by(user_id: current_user.id)
  end

  private

  def order_params
    params.permit(:user_id, :product_id, :address_id, :card_id, :quantity, :price)
  end

  def set_user
    @user = current_user
  end

  def set_cart
    @cart = current_cart
    @cart_detail = @cart.cart_details
  end

  def set_card
    @card = Card.find_by(user_id: current_user.id)
  end

  def set_address
    @address = Address.find_by(user_id: current_user.id)
  end

  def user_signed_in
    unless user_signed_in?
      redirect_to cart_path(@cart.id), alert: "レジに進むにはログインが必要です"
    end
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/confirm.html.haml
.order.confirmbg
  .order__box
    .order__box__title
      Thank you for choosing BeYourCover
    .order__box__body
      お届け先
      .order__box__body__text
        = "氏名 : #{@order.address.destination_last + @order.address.destination_first}"
      .order__box__body__text
        = "ふりがな : #{@order.address.destination_last_kana + @order.address.destination_first_kana}"
      .order__box__body__text
        = "Eメール : #{@order.user.email}"
      .order__box__body__text
        = "郵便番号 : #{@order.address.post_code}"
      - if @order.address.building.present?
        .order__box__body__text
          = "住所 : #{@order.address.prefecture.name + @order.address.city + @order.address.address + @order.address.building}"
      - else
        .order__box__body__text
          = "住所 : #{@order.address.prefecture.name + @order.address.city + @order.address.address}"
      .order__box__body
        購入商品
      - @order.order_details.each do |detail|
        -# .confirmation__box__body__text
        -#   = "受付時間 : #{@order.created_at.strftime('%Y/%m/%d/ %H:%M:%S')}"
        -# .confirmation__box__body__text
        -#   = "オーダー番号 : #{@order.id}"
        .order__box__body__text
          = "#{detail.product.name}  × #{detail.quantity}：¥#{(detail.product.price*detail.quantity).to_s(:delimited, delimiter: ',')}"
      .order__box__body__text
        = "お支払い合計 : ¥#{(@order.price.to_s(:delimited, delimiter: ','))}"
        %span (税込・送料込)
      %br
      .order__box__body__text
        ＊購入明細をご登録いただきましたメールアドレスにも記載しておりますのでご確認くださいませ。
    .showMain__content__topContent__itemBox__detail__btn
      = link_to "トップページへ戻る",root_path, data: {"turbolinks"=>false}, class: "showMain__content__topContent__itemBox__detail__btn__purchaseBtn"

app/views/orders/index.html.haml
-# = render layout: "users/show" do
-#   .orderedItems
-#     .orderedItems__content
-#       .orderedItems__content__title
-#         注文履歴
-#       - if @orders.count == 0
-#         .orderedItems__content__nothing
-#           ご注文履歴はございません
-#       - else
-#         %table.orderedItems__content__table{border: 2}
-#           %thead
-#             %tr
-#               %th 購入日
-#               %th 注文番号
-#               %th 状況
-#               %th 購入商品
-#               %th 合計金額(税込)
-#             %tbody
-#               - @orders.each do |order|
-#               - product = Product.find(order.order_details.to_a[0][:product_id])
-#                 %tr
-#                   %td= order.created_at.strftime('%Y/%m/%d')
-#                   %td= order.id
-#                   %td= order.status
-#                   %td
-#                     - if order.order_details.to_a.size == 1
-#                       = link_to "#{product.namejap}", order_details_path(order_id: order.id)
-#                     -else 
-#                       = link_to "#{product.namejap} など #{order.order_details.to_a.size}件", order_details_path(order_id: order.id)
-#                   -# %td= "¥ #{convertToJPY(order.price)}"

app/views/orders/new.html.haml
= render 'layouts/navbar'
= render 'layouts/notification'
.order
  .order__box
    .order__box__title
      CHECK OUT
    .order__box__body
      .order__box__subtitle
        お届け先住所
      - if @address.present?
        .order__box__body__text
          = "〒 #{@address.post_code}"
        .order__box__body__text
          = @address.prefecture.name + @address.city + @address.address + @address.building
        .order__box__body__text
          = @address.destination_last + @address.destination_first
        .order__box__body__text
          = link_to "お届け先を変更", edit_addresses_path(@address.id), class: "change-btn"
      - else
        .order__box__body__text
          = link_to "登録する", addresses_path, data: {"turbolinks"=>false}, class: "change-btn"
    .order__box__card
      登録カード
      - if @card.present?
        .order__box__card__text
          = image_tag "#{@card_src}", width: 50, height: 40
        .order__box__body__text
          = "カード番号：**** **** **** " + @card_info.last4
        .order__box__card__text
          = "有効期限：" + @exp_month + " / " + @exp_year
          .order__box__card__text__btn
            = link_to "カードを変更", new_card_path, class: "change-btn"
      - else
        .order__box__card__text__btn
          = link_to "登録する", new_card_path, class: "change-btn"
    .order__box__product
      .order__box__subtitle
        ご注文内容
      - @cart_details.each do |cart_detail|
        .order__box__product__detail
          .order__box__product__detail__pic
            = image_tag cart_detail.product.images[0].item.url, width: 80, height: 100
          .order__box__product__detail__text
            .order__box__product__detail__text__line
              = cart_detail.product.name
            .order__box__product__detail__text__line
              = "数量：#{cart_detail.quantity}"
            .order__box__product__detail__text__line
              = "小計：¥#{cart_detail.total_price.to_s(:delimited, delimiter: ',')}"
            .order__box__product__detail__text__line
              %span (税込・送料込)
    .order__box__total
      = "合計 : ¥#{(@cart.total_price.to_s(:delimited, delimiter: ','))}"
      .order__box__total__detail
        %span (税込・送料込)
    .showMain__content__topContent__itemBox__detail__btn
      - if @card.present? && @address.present?
        = button_to "購入する", orders_path, class: "showMain__content__topContent__itemBox__detail__btn__purchaseBtn", params: {user_id: current_user.id, address_id: @address.id, card_id: @card.id, price: @cart.total_price, quantity: @cart.total_number}
      - else
        %span ※ 購入には送付先住所・カード情報の登録が必要です
  .showMain__content__topContent__itemBox__detail__btn
    %input{onclick: "history.back()", type: "button", value: "前のページへ戻る", class: 'showMain__content__topContent__itemBox__detail__btn__purchaseBtn'}