config/routes.rb
Rails.application.routes.draw do
  get 'pages/about'
  devise_for :users, controllers: {
    registrations: "users/registrations", sessions: "users/sessions", confirmations: "users/confirmations" }
  root "products#index"
  devise_scope :user do
    get "new_user", to: "users/registrations#new_user"
    post "new_user", to: "users/registrations#create_user"
    get "addresses", to: "users/registrations#new_address"
    post "addresses", to: "users/registrations#create_address"
    get "edit_addresses", to: "users/registrations#edit_address"
    patch "edit_addresses", to: "users/registrations#update_address"
  end

  resources :products do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    member do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
  end

  resources :categories, only: [:index, :show]

  resources :cards, only: [:new, :create, :show, :destroy]

  resources :carts, only: [:show, :destroy] do
    collection do
      post 'add_product'
    end
  end

  resources :orders, only: [:new, :create, :index] do
    collection do
      get 'confirm'
    end
  end 

  resources :order_details, only: :index

  resources :cart_details

  get 'about', to: 'pages#about'
  get 'privacy', to: 'pages#privacy'
  # get 'faq', to: 'pages#faq'
  get 'delivery', to: 'pages#delivery'
  get 'refund', to: 'pages#refund'
  get 'terms_of_service', to: 'pages#terms_of_service'
  get 'tokushoho', to: 'pages#tokushoho'
  get 'inquiry', to: 'pages#inquiry'
  get 'search', to: 'pages#search'
  get 'search_result', to: 'pages#search_result'

end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_details, dependent: :destroy

  def add_product(product_id)
    cart_details.find_or_initialize_by(product_id: product_id)
  end

  def add_quantity(quanitty)
    cart_details.find_or_initialize_by(quantity: quantity)
  end

  def total_price
    cart_details.to_a.sum{|product| product.total_price}
  end

  def total_number
    cart_details.to_a.sum{|product| product.quantity}
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart_detail!, only: [:add_product, :update_product, :destroy]
  before_action :set_user
  before_action :set_cart

  def show
    @cart_details = @cart.cart_details
    if user_signed_in?
      @user = User.find(current_user.id)
      @address = Address.find(current_user.id)
    end
  end
  
  def add_product
    @cart_detail = current_cart.cart_details.build(product_id: params[:product_id]) if @cart_detail.blank?
    @cart_detail.quantity += params[:quantity].to_i
    @cart_detail.save!
    redirect_to current_cart
  end

  def destroy
    @cart_detail.destroy
    redirect_to current_cart
  end


  private

  def set_cart_detail!
    @cart_detail = current_cart.cart_details.find_by(product_id: params[:product_id])
  end

  def set_user
    @user = current_user
  end

  def set_cart
    @cart = current_cart
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/show.html.haml
= render 'layouts/navbar'
.space
.checkout
  .checkout__title
    My Cart
  - if @cart_details.count == 0
    .checkout__empty
      No Items...
    .showMain__content__topContent__itemBox__detail__btn
      %input{onclick: "history.back()", type: "button", value: "前のページへ戻る", class: 'showMain__content__topContent__itemBox__detail__btn__purchaseBtn'}
  - else
    - @cart_details.each do |cart_detail|
      .checkout__product
        .checkout__product__image.col-md-3.col-12
          = image_tag cart_detail.product.images[0].item.url, width: 120, height: 150
        .checkout__product__details.col-md-9.col-12
          .checkout__product__details__text.col-sm-6.col-12
            %p
              商品名：
              = cart_detail.product.name
            %p
              カテゴリー：
              = cart_detail.product.category.name
            %p
              ブランド：
              = cart_detail.product.brand
          .checkout__product__details__quantity.col-sm-3.col-12
            %p
              数量：
              = form_with url: cart_detail_path(cart_detail), method: :patch, local: true do |f|
                - if cart_detail.product.stock > 1
                  = f.number_field :quantity ,placeholder: "#{cart_detail.quantity}", value: "#{cart_detail.quantity}", min: 1, max: cart_detail.product.stock, class: "cart-quantity"
                  = f.submit "変更", {class: "cart-edit"}
                - else
                  = cart_detail.product.stock
                  ラスト
          .checkout__product__details__price.col-sm-3.col-12
            %p
              小計：
              = "¥#{cart_detail.total_price.to_s(:delimited, delimiter: ',')}"
              %span (税込)
              %br
              %span 送料
              = cart_detail.product.postage
            = button_to '削除', cart_detail_path(cart_detail), method: :delete, data: { confirm: '削除しますか?' }, class: "cart-delete"
    .checkout__total
      = "合計 : ¥#{(@cart.total_price.to_s(:delimited, delimiter: ','))}"
    - if user_signed_in? 
      .showMain__content__topContent__itemBox__detail__btn
        = link_to "レジに進む", new_order_path, class: "showMain__content__topContent__itemBox__detail__btn__purchaseBtn"
    - else
      .showMain__content__topContent__itemBox__detail__btn
        = link_to "新規登録", new_user_registration_path, class:'showMain__content__topContent__itemBox__detail__btn__purchaseBtn'
      .showMain__content__topContent__itemBox__detail__btn
        = link_to "ログイン", new_user_session_path, class:'showMain__content__topContent__itemBox__detail__btn__purchaseBtn'
    .showMain__content__topContent__itemBox__detail__btn
      = link_to "他の商品を見る", root_path, class: "showMain__content__topContent__itemBox__detail__btn__purchaseBtn"