config/routes.rb
Rails.application.routes.draw do
  get 'pages/about'
  devise_for :users, controllers: {
    registrations: "users/registrations", sessions: "users/sessions", confirmations: "users/confirmations" }
  root "products#index"
  devise_scope :user do
    get "new_user", to: "users/registrations#new_user"
    post "new_user", to: "users/registrations#create_user"
    get "addresses", to: "users/registrations#new_address"
    post "addresses", to: "users/registrations#create_address"
    get "edit_addresses", to: "users/registrations#edit_address"
    patch "edit_addresses", to: "users/registrations#update_address"
  end

  resources :products do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    member do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
  end

  resources :categories, only: [:index, :show]

  resources :cards, only: [:new, :create, :show, :destroy]

  resources :carts, only: [:show, :destroy] do
    collection do
      post 'add_product'
    end
  end

  resources :orders, only: [:new, :create, :index] do
    collection do
      get 'confirm'
    end
  end 

  resources :order_details, only: :index

  resources :cart_details

  get 'about', to: 'pages#about'
  get 'privacy', to: 'pages#privacy'
  # get 'faq', to: 'pages#faq'
  get 'delivery', to: 'pages#delivery'
  get 'refund', to: 'pages#refund'
  get 'terms_of_service', to: 'pages#terms_of_service'
  get 'tokushoho', to: 'pages#tokushoho'
  get 'inquiry', to: 'pages#inquiry'
  get 'search', to: 'pages#search'
  get 'search_result', to: 'pages#search_result'

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
  has_ancestry
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: :show
  before_action :set_cart

  def index
    @parents = Category.where(ancestry: nil)
    @products = Product.all
    @categories = Product.includes(:images).order("created_at DESC")
  end

  def show
    @parents = Category.where(ancestry: nil)
    if @category.has_children?
      @products = Product.includes(:images).order("created_at DESC").where(category_id: @category.descendants)
    else
      @products = Product.includes(:images).order("created_at DESC").where(category_id: @category)
    end

    if user_signed_in?
      @user = User.find(current_user.id)
      @address = Address.find(current_user.id)
    end
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def set_cart
    @cart = current_cart
  end
end

app/views/categories/show.html.haml
= render 'layouts/navbar'
= render 'layouts/notification'
.space
.container-fluid.mt-5
  .row
    .contentCat.col-12
      .contentCat__show
        = "#{@category.name}の商品一覧"
    - if user_signed_in? && current_user.admin?
      .products
        - @products.each do |p|
          - if p.stock == 0
            .no-stock.col-md-4.col-sm-6.col-6
              .no-stock__msg
                No Stock
              .no-stock__admin
                = link_to 'Edit', edit_product_path(p)
                = link_to 'Destroy', p, method: :delete, data: { confirm: 'Are you sure?' }
              .no-stock__name
                %p
                  = p.name
                %p
                  在庫：
                  = p.stock
          - else
            .product.col-md-4.col-sm-6.col-6
              .product__front
                = link_to product_path(p) do
                  .product__front__imgbox
                    = image_tag p.images[0].item.url
                .product__title
                  = p.name
                .product__price
                  = "#{p.price.to_s(:delimited, delimiter: ',')}円"
                  %br
                  %span (税込・送料込)
              = link_to 'Edit', edit_product_path(p), class: "no-stock__admin"
              = link_to 'Destroy', p, method: :delete, data: { confirm: 'Are you sure?' }, class: "no-stock__admin"
    - else
      .products
        - @products.each do |p|
          - if p.stock == 0
          - else
            .product.col-md-4.col-sm-6.col-6
              .product__front
                = link_to product_path(p) do
                  .product__front__imgbox
                    = image_tag p.images[0].item.url
                .product__title
                  = p.name
                .product__price
                  = "#{p.price.to_s(:delimited, delimiter: ',')}円"
                  %br
                  %span (税込・送料込)
    .button
      %input{onclick: "history.back()", type: "button", value: "前のページへ戻る", class: 'showMain__content__topContent__itemBox__detail__btn__purchaseBtn'}