config/routes.rb
Rails.application.routes.draw do
  get 'pages/about'
  devise_for :users, controllers: {
    registrations: "users/registrations", sessions: "users/sessions", confirmations: "users/confirmations" }
  root "products#index"
  devise_scope :user do
    get "new_user", to: "users/registrations#new_user"
    post "new_user", to: "users/registrations#create_user"
    get "addresses", to: "users/registrations#new_address"
    post "addresses", to: "users/registrations#create_address"
    get "edit_addresses", to: "users/registrations#edit_address"
    patch "edit_addresses", to: "users/registrations#update_address"
  end

  resources :products do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    member do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
  end

  resources :categories, only: [:index, :show]

  resources :cards, only: [:new, :create, :show, :destroy]

  resources :carts, only: [:show, :destroy] do
    collection do
      post 'add_product'
    end
  end

  resources :orders, only: [:new, :create, :index] do
    collection do
      get 'confirm'
    end
  end 

  resources :order_details, only: :index

  resources :cart_details

  get 'about', to: 'pages#about'
  get 'privacy', to: 'pages#privacy'
  # get 'faq', to: 'pages#faq'
  get 'delivery', to: 'pages#delivery'
  get 'refund', to: 'pages#refund'
  get 'terms_of_service', to: 'pages#terms_of_service'
  get 'tokushoho', to: 'pages#tokushoho'
  get 'inquiry', to: 'pages#inquiry'
  get 'search', to: 'pages#search'
  get 'search_result', to: 'pages#search_result'

end

app/views/layouts/_footer.html.haml
.container-fluid.px-5
  .row
    .col-md-6.col-sm-12
      .msg
        About Us
      .row
        .col-12
          .msg__text
            あなたの生活を、守り彩る、そんなアイテムを取り揃えております。
            %br
            お気に入りのアイテムをお探しするお役に立てますように。
        .social.col-12.mt-3
          = link_to '', "https://instagram.com/masatakakuwada0602", class: 'fab fa-instagram', target: '_blank'
    .col-md-6.col-sm-12
      .msg
        User Guide
      .guide
        .msg__text
          =link_to 'プライバシーポリシー', privacy_path, class: 'msg__text__line'
          -# =link_to 'よくあるご質問', faq_path, class: 'msg__text__line'
          =link_to '配送について', delivery_path, class: 'msg__text__line'
          =link_to '返金・返品について', refund_path, class: 'msg__text__line'
          =link_to '利用規約', terms_of_service_path, class: 'msg__text__line'
          =link_to '特定商取引法に基づく記載', tokushoho_path, class: 'msg__text__line'
          =link_to 'お問い合わせ', 'https://docs.google.com/forms/d/e/1FAIpQLSeqsbPCALipBsSX2wT9S1FpqyTcloNH6iJEopuPtMHdpqXyPw/viewform', class: 'msg__text__line', target: '_blank'
.footer
  .footer-card
    .card__box__body__image
      %li
        = image_tag 'https://www-mercari-jp.akamaized.net/assets/img/card/visa.svg?238737266', class: 'card__box__body__image__visa'
      %li
        = image_tag 'https://www-mercari-jp.akamaized.net/assets/img/card/master-card.svg?238737266', class: 'card__box__body__image__masterCard'
      %li
        = image_tag 'https://www-mercari-jp.akamaized.net/assets/img/card/jcb.svg?238737266', class: 'card__box__body__image__jcb'
      %li
        = image_tag 'https://www-mercari-jp.akamaized.net/assets/img/card/american_express.svg?238737266', class: 'card__box__body__image__americanExpress'
      %li
        = image_tag 'https://www-mercari-jp.akamaized.net/assets/img/card/dinersclub.svg?238737266', class: 'card__box__body__image__dinersclub'
      %li
        = image_tag 'https://www-mercari-jp.akamaized.net/assets/img/card/discover.svg?238737266', class: 'card__box__body__image__discover'
  .footer-bottom
    Copyright © BeYourCover 2020

app/views/layouts/_navbar.html.haml
%body
  %header
    .container-fluid
      .row
        .site-title
          = link_to "BeYourCover", root_path, class: 'home'
        .site-nav
          #cart.cart-head-btn
            = link_to cart_path(@cart.id), class: "cart" do
              %i.fas.fa-shopping-cart
                - if @cart.total_number > 0
                  = @cart.total_number
                - else

          #search.search-head-btn
            = link_to search_path, class: "search" do
              %i.fas.fa-search
          #menu-bar
            #menu.menu
              #bar1.bar
              #bar2.bar
              #bar3.bar
            %div
              %ul#nav.nav.nav-sm
                - if current_user
                  .mainnav
                    %li= link_to "home", root_path, class: 'select'
                    %li= link_to "about", about_path, class: 'select'
                    %li
                      %a#subnav.select.drop
                        = current_user.name
                        %i.fas.fa-caret-down
                  .subnav
                    %li
                      .dds
                        - if current_user.admin
                          = link_to "New Product", new_product_path, class: 'dds__select'
                        = link_to "Account Settings", edit_user_registration_path, class: 'dds__select'
                        - if @address.present?
                          = link_to "Address Settings", edit_addresses_path(@address.id), class: "dds__select"
                        - if @card.present?
                          = link_to "Card Setting", new_card_path, class: "dds__select"
                        - else
                          = link_to "Card Setting", new_card_path, class: "dds__select"
                        = link_to "Logout", destroy_user_session_path, class:'dds__select', method: :delete
                - else
                  .mainnav
                    %li= link_to "home", root_path, class: 'select'
                    %li= link_to "about", about_path, class: 'select'
                    %li.nav-item
                      = link_to "Signup", new_user_path, class:'select'
                    %li.nav-item
                      = link_to "Signin", new_user_session_path, class:'select'
        #menu-bg.menu-bg

app/views/layouts/_notification.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Beyourcover
    %script{src: "https://js.pay.jp/", type: "text/javascript"}
    = include_gon(init: true)
    = csrf_meta_tags
    = csp_meta_tag
    / mobile
    %meta{:content => "width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0", :name => "viewport"}/
    / FontAwsome
    %link{:crossorigin => "anonymous", :href => "https://use.fontawesome.com/releases/v5.8.2/css/all.css", :integrity => "sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay", :rel => "stylesheet"}/
    / bootstrap
    = stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    /google analytics
    = analytics_init if Rails.env.production?
  %body
    = yield
    %footer
      = render 'layouts/footer'
      = javascript_include_tag 'application'
      = javascript_include_tag 'products'
      = javascript_include_tag 'categories'
      = javascript_include_tag 'cards'